# Generated by Django 2.1.4 on 2018-12-16 05:25

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uri', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pub_date', models.DateField()),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('uri', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='mag.Tag'),
        ),
    ]
